# title: Tyler Craig
# email: TylerCraigSec@proton.me
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "dnd.tylercraig.me"
github_username:  tjhamlet
avatar: img/sidebardImage.png

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

# Build settings
# remote_theme: pages-themes/slate@v0.2.0
# theme: minima
theme: jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/